BLOCK_SIZE: 2048
# Max amount of bytes to read from the buffer at a time.

NODE_TIMEOUT: 20
# Timeout (seconds) for a node to be considered dead.

VOTE_TIMEOUT: 60
# Timeout (seconds) for a node to wait for a vote.

AGGREGATION_TIMEOUT: 60
# Timeout (seconds) for a node to wait for other models. Timeout starts when the first model is added.

HEARTBEAT_PERIOD: 4
# Period (seconds) for the node to send a heartbeat.

HEARTBEATER_REFRESH_NEIGHBORS_BY_PERIOD: 4
# Times by period to refresh the neighbors list.

WAIT_HEARTBEATS_CONVERGENCE: 10
# Time (seconds) to wait for the heartbeats to converge.

TRAIN_SET_SIZE: 10
# Size of the training set.

TRAIN_SET_CONNECT_TIMEOUT: 5
# Timeout (seconds) to wait for a node to connect to the training set.

AMOUNT_LAST_MESSAGES_SAVED: 100
# Amount of last messages saved. Used to avoid gossiping cycles.

GOSSIP_MESSAGES_FREC: 100
# Frequency of gossiping messages (times by second).

GOSSIP_MESSAGES_PER_ROUND: 100
# Amount of gossip messages per round.

GOSSIP_EXIT_ON_X_EQUAL_ROUNDS: 20
# Amount of equal rounds to exit gossiping. Careful, a low value can cause an early stop of gossiping.

GOSSIP_MODELS_FREC: 1
# Frequency of gossiping models (times by second).

GOSSIP_MODELS_PER_ROUND: 2
# Amount of gossip models per round.

common_args:
  training_type: "simulation"
  random_seed: 0
  config_version: "development"

data_args:
  dataset: "MNIST"
  data_cache_dir: "/data/MNIST"
  partition_method: "noniid"
  partition_alpha: 0.5

model_args:
  model: "lr"

train_args:
  federated_optimizer: "FedAvg"
  client_id_list: "[]"
  client_num_in_total: 1000
  client_num_per_round: 10
  comm_round: 200
  epochs: 1
  batch_size: 10
  client_optimizer: sgd
  learning_rate: 0.03
  weight_decay: 0.001

validation_args:
  frequency_of_the_test: 5

device_args:
  using_gpu: true
  gpu_id: 0

tracking_args:
  enable_tracking: true
  enable_wandb: false
  wandb_key: [your wandb key]
  wandb_entity: enriquetomasmb
  wandb_project: simulation
  run_name: simulation_dfl